### ISSUE TITLE
Unable tolocate input assembly `C:Program` or one of its depedency

### ISSUE THREAD

**Issue by reidsneo** [wmltogether/VPKIconExtInstalller#3]
problem as title said, while installing the shell extension
.vpk is not associated to this program still display blank white icon file

My Computer :
-Windows 8
-UAC Enable
-Microsoft Dot Net 4.5 installed (I have visual studio 2012 installed btw)

![unable](https://cloud.githubusercontent.com/assets/12298979/21959708/9fe989f6-db0a-11e6-8727-5da1f34487a1.png)

**Comment by Masamune3210** [comment]
where do you have the files extracted to?

**Comment by reidsneo** [comment]
extracted to C:\Program Files (x86)\VPKicon

my system is 64bit
my UAC is enabled but I run it as admin

**Comment by Masamune3210** [comment]
extract it to a folder without spaces in its path, and try again

**Comment by reidsneo** [comment]
Yeah I know, program working good btw, just want to report there is a bug with the path

**Comment by wmltogether** [comment]
Yeah, Got it, I forgot to add @"" for path while creating  REGASM process.

**Comment by SiTWulf** [comment]
@wmltogether We need a fast bugfix for this.
Some people like me using a Spanish version of Windows, and need this to be fixed to work perfect.

**Comment by wmltogether** [comment]
@SiTWulf The code has been fixed already .Just recompile using Visual Studio and reinstall it. I'll update the installer exe soon.

**Comment by wmltogether** [comment]
Okey. Installer updated.
