### ISSUE TITLE
Bugs with ZIP file Format

### ISSUE THREAD

**Issue by SiTWulf** [wmltogether/VPKIconExtInstalller#4]
When i install this DLL i get my ZIP files with bad icon and VPK menu in right click.

**Comment by wmltogether** [comment]
Thanks for the issue, but Sorry I don't really know the problem. 
I did't add *.zip File Extensions in the code, and didn't know how it could be registered to *.zip files.
`[COMServerAssociation(AssociationType.ClassOfExtension, ".vpk")]`
This is the only extension name which I added.
Could you upload a screenshot ?

**Comment by SiTWulf** [comment]
Hi.
No need for now... you fixed the problem with the update: v20170123.0
You can close this Bug...
Tahnks!
